### ISSUE TITLE
Twitter button (at least on demo) blocked by Chrome's popup blocker

### ISSUE THREAD

**Issue by j-ro** [filamentgroup/SocialCount#1]
Great code! Found a few issues before I can use it, though. Wanted to get them over to you to make sure they're on your radar...

First, when I click the twitter button after rollover and population of the "real" social plugin, the window created by the button is blocked by chrome's popup blocker (at least on your demo page). Seems like that's a bit detriment to use of those buttons.

**Comment by zachleat** [comment]
This repository has been moved into an unmaintained state and as such all open issues and pull requests will now be closed!

We’re happy to link to forks!
