### ISSUE TITLE
Facebook: "(#12) fql is deprecated for versions v2.1 and higher"

### ISSUE THREAD

**Issue by hugovk** [filamentgroup/SocialCount#105]
This plugin calls Facebook's Graph API without specifying a version number:

https://github.com/filamentgroup/SocialCount/blob/9a4bf84cd97f95c0e0a7f36bdff6188319d3ff1e/dist/service/SocialCount.php#L16

Facebook say:

> **What happens if I don't specify a version for an API?**
>
> We refer to this as an **unversioned** call. An unversioned call will default to the oldest available version of the API. Consider this hypothetical life cycle of API versions:
> 
> ![image](https://user-images.githubusercontent.com/1324225/32659190-2e208a88-c626-11e7-97e4-aa1362093737.png)
> 
> An unversioned call will always point to the oldest version still available at the top of the chart. This is currently v2.1, but after two years it'll be v2.2, then v2.3, etc.
> 
> Because of this, our recommendation is to always specify versions when making calls, where possible.

The latest Graph API version is v2.11, released [this week](https://developers.facebook.com/docs/graph-api/changelog) and v2.1 has been [EOL since 2016-10-30](https://developers.facebook.com/docs/graph-api/changelog/archive).

I've created PR https://github.com/filamentgroup/SocialCount/pull/104 to version the call to the latest 2.11, but this project should be updated to replace the FQL call to one Graphs API directly, eg. https://stackoverflow.com/a/26571100/724176, as FQL will likely be removed at some point.

**Comment by zachleat** [comment]
Sorry @hugovk, I appreciate the help but unfortunately this repository has been moved into an unmaintained state and as such all open issues and pull requests will now be closed!

We’re happy to link to forks!
