### ISSUE TITLE
Twitter API Restricted

### ISSUE THREAD

**Issue by ddrager** [filamentgroup/SocialCount#20]
The Twitter API url used in SocialCount works when only minimal calls are made to the Twitter API. After throwing several hundred requests at it (probably 150, the logged-out API limit) I began to receive errors. 

After checking out the dev documents, it was stated several times that using this method to get Tweet counts is not authorized and that developers should not use it. 

They stated that the proper way is to set up an Application in your account and then use the Streaming API to get these counts. 

Of course, that is all well and good, but it is considerably more difficult than currently so I'm not sure what a good solution to this is. Just wanted to open an issue to let others know about this, because it will begin to fail if you throw a lot of requests at it.

**Comment by zachleat** [comment]
Closing in favor of #54. Thanks!
