### ISSUE TITLE
Ability to define a hovering time until activation

### ISSUE THREAD

**Issue by Schepp** [filamentgroup/SocialCount#27]
In order to prevent users from accidentially activating a button it would be great if one would be able to define a timespan of continous hovering before a button activates. 

A typical scenario where this would help is when a user moves the mouse accross the screen and then also passes accross the button. Longer hovering and/or a click would guarantee that it is the user's intention to activate it.

Background: Here in Germany sites are not allowed to activate social plugins without permission from the user, because of privacy reasons. Not complying with that can get very expensive.

**Comment by zachleat** [comment]
Configurable with SocialCount.hoverDelay

**Comment by Schepp** [comment]
<3
