### ISSUE TITLE
Info bubble when activated by click

### ISSUE THREAD

**Issue by Schepp** [filamentgroup/SocialCount#28]
When Social Count is configured to activate on click it should tell people when they click that they just activated the button and that they now need to click again to complete their action. Currently there is no indication of what is happening, so people think they have already shared the page with their first click.

**Comment by zachleat** [comment]
I would accept a PR for this, but I don’t think we’ll implement this ourselves. The hover behavior is the default. Sorry!

I’d recommend using the default share link URLs rather than SocialCount inline widgets if this is required.
