### ISSUE TITLE
Google+ button markup needs data-href specified

### ISSUE THREAD

**Issue by Schepp** [filamentgroup/SocialCount#30]
Code needs to be changed to

```
<div class="g-plusone" data-size="medium" data-annotation="none" data-href="' + url + '"></div>
```

since otherwise the button is prepopulated with the wrong URL when your site is using hashbangs (or anchors).

**Comment by zachleat** [comment]
Better late than never!

![](https://dl.dropboxusercontent.com/u/361291/gifs/shame_cube.gif)

**Comment by Schepp** [comment]
![Corner of Shame](http://jilliancolemanwheeler.com/wp-content/uploads/2012/12/Child_corner2.jpg)
