### ISSUE TITLE
Facebook Recommend action not supported

### ISSUE THREAD

**Issue by sbaechler** [filamentgroup/SocialCount#46]
Facebook now opens a popup similar to the share button when the action of the like button is set to recommend.
https://developers.facebook.com/docs/plugins/like-button/

This does not happen when the button is redered using SocialCount even if data-facebook-action is set to recommend.

**Comment by zachleat** [comment]
We’ve upgraded SocialCount to use the Facebook JS API rather than the iframe widget. This should work fine now. Let me know if it doesn’t work for you!
