### ISSUE TITLE
Demo Doesn't Work

### ISSUE THREAD

**Issue by aleemb** [filamentgroup/SocialCount#53]
The demo page just shows some labels and nothing else at the moment.

**Comment by zachleat** [comment]
Really? Can you give more information? I see this:

![image](https://cloud.githubusercontent.com/assets/39355/5649381/f2afd7ea-965a-11e4-9e1d-fbed31013800.png)

http://master.origin.socialcount.fgtest.com/examples/

**Comment by aleemb** [comment]
It was uBlock software, my bad.

**Comment by zachleat** [comment]
No worries!
