### ISSUE TITLE
Add option to fetch counts without server side script

### ISSUE THREAD

**Issue by aleemb** [filamentgroup/SocialCount#54]
It's possible to get like counts quite trivially via JS:
http://codepen.io/andreasstorm/pen/iefKk/

Why is the server-side code required? Would like to understand if I may have overlooked something.

**Comment by zachleat** [comment]
Hmm, I’m not sure those APIs existed when this plugin was created. Good to see that changed! I’m worried about the issues with one HTTP request per service, however, but this seems like a good option for someone that doesn’t have a server side option! I’m going to edit the title of this ticket to reflect work that could improve the utility.

**Comment by aleemb** [comment]
> I’m worried about the issues with one HTTP request per service

It's a valid concern but I don't think that really matters much. The JS calls are async and non-blocking.

**Comment by zachleat** [comment]
I’m learning towards your thinking that the positives of this outweigh the negatives.

A few other things to keep in mind:
* Note Max Connections on [Browserscope](http://www.browserscope.org/?category=network). (Max connections per hostname is kinda irrelevant here since the requests are all to different domains)
* This will potentially introduce N new DNS lookups too. (Where N is the number of social networks you’re using)

Some people use SocialCount on a list-style page where it isn’t just one instance of the component. So this would be N-1 more requests per instance of the component. So if you had 10 articles on your blog home page and used SocialCount for each, it’d be 40 requests with 4 social networks instead of 10 requests with the aggregate method.

**Comment by ddrager** [comment]
I also agree with this (as author of https://github.com/filamentgroup/SocialCount/issues/20) and feel that Twitter prefers this method (for some reason). It may be possible to aggregate all social buttons loaded on the page and do a single request to the Twitter api for the counts; haven't read up on the Twitter API in a bit. 

We run a high volume site so we hit the 150 limit very quickly. Caching helped but there are many other pages making requests so the Twitter API limited it to the point where we couldn't do the request server side.

**Comment by aleemb** [comment]
I don't mean to undermine the efforts that have gone into this plugin, but really I don't see any need for it anymore.

There reasons provided for server-side solutions are seem contrived, micro optimisations. There is no little to no pragmatic value for a server-side solution. However, moving to client-side only may make this project and most of it's codebase obsolete.

1.  The big social networks have CDNs and edge-side caching. FB, Google, etc load extremely fast no matter which country you are in. This goes even beyond CDNs as the biggest players usually have peering agreements. So if you are hitting your Linode server in EU do load social icons, you'll be much slower than directly hitting FB, etc.

2. JS offers async, defer.

3. DNS lookups is not an issue considering these widgets are loaded across nearly every site you visit.

4. Because of (3) the assets for the social sites are cached (and it's possible their caching policy is well-thought out to use aggressive caching or as best suits the common use-case).

5. Routing through your server will always take longer. The request needs to be made from client to your server. Then from your server to the network of choice. And then back to the client. All sorts of bottlenecks and issues can come up because of your server. Not the least of which is API limits.

6. The setup required to get this going is just a PITA (server provisioning, API Keys, keeping up-to-date with this repo)

7. Your server is yet another point of failure for this. Directly hitting the networks is better because of all the above points and also because they have far better redundancy built in.

I am not sure there is any reason to use this library today when you can do it in a few lines of JS via http://codepen.io/andreasstorm/pen/iefKk/.

**Comment by zachleat** [comment]
Yes, I will agree that it is probably time to switch the default from a server side service to client side for the count retrieval.

However, I strongly disagree that the count service to the client switch renders this “codebase obsolete.” Counts have always been an optional piece of SocialCount (despite the unfortunate name). The primary benefit to SocialCount is the on-demand loading of hefty native widgets. If any argument were to be made that the entirety of the SocialCount plugin were to be obsolete, the only logical alternative would not to use the native widgets at all—and instead opt to only use the direct sharing URLs. This appears to be what you’ve done in your codepen demo, but that discussion is not the scope of this ticket. (Using native widgets has other beneficial side effects—lower barrier to share completion, better ranking in search results with G+, etc etc). If you’d like to discuss that topic, please open a new ticket.

An ajax request to retrieve counts will obviously be much smaller than the 300+kB required to load the widgets themselves.

Again, I’m not against this change. It will come in due time and a PR will probably help it along.

**Comment by zachleat** [comment]
Removed per discussion in #93
