### ISSUE TITLE
Facebook balloon hidden

### ISSUE THREAD

**Issue by andjo** [filamentgroup/SocialCount#60]
The balloon popup that opens from the Facebook button on desktop devices is mostly hidden due to overflow:hidden on .socialcount.

This is currently reproducible on the demo page.

**Comment by juukie** [comment]
Having the same issue. You should be logged in already to see it happen.

**Comment by juukie** [comment]
This is my temporary fix:

~~~
.socialcount {
    overflow: visible;
}

.socialcount > li.loaded {
    .scbutton {
        display: none;
    }

    &:hover {
        > a {
            display: none;
        }

        .scbutton {
            display: block;
        }
    }
}
~~~

**Comment by zachleat** [comment]
This repository has been moved into an unmaintained state and as such all open issues and pull requests will now be closed!

We’re happy to link to forks!
