### ISSUE TITLE
Init problems when SocialCount is loaded too late.

### ISSUE THREAD

**Issue by andjo** [filamentgroup/SocialCount#61]
If socialcount.js is executed after jQuery.ready() has fired no plugins will work.

Since the plugins are added at the end of the file, and "$(function() { ..." on line 327 will execute immediately when $().ready() has already been fired, init() will be called with empty plugins.

In my case this is happening because I'm using https://github.com/Cerdic/jQl to load jQuery and  dependent code asynchronously.

**Comment by mrsoto** [comment]
I've the same problem more than a year from this issue. SocialCount looks to be abandoned.

**Comment by zachleat** [comment]
This repository has been moved into an unmaintained state and as such all open issues and pull requests will now be closed!

We’re happy to link to forks!
