### ISSUE TITLE
Firefox’s tracking protection causes loading indicator to keep running infinitely

### ISSUE THREAD

**Issue by simevidas** [filamentgroup/SocialCount#68]
You can see the issue [on this page](http://master.origin.socialcount.fgtest.com/examples/) in Firefox with `privacy.trackingprotection.enabled` flag (or in Private Browsing mode).

Demo (gif): https://twitter.com/simevidas/status/668894388903391232

**Comment by zachleat** [comment]
This repository has been moved into an unmaintained state and as such all open issues and pull requests will now be closed!

We’re happy to link to forks!
