### ISSUE TITLE
'Follow' variety

### ISSUE THREAD

**Issue by japborst** [filamentgroup/SocialCount#9]
Hi,

I really like the social buttons in this way. I was wondering, though, if it would be possible to do the same for Twitter follow and maybe G+ 'add to circle'. For Facebook this is not really necessary, as - I believe - setting YOUR-URL as the FB page URL will like the page in question. 

Thanks!

**Comment by zachleat** [comment]
This repository has been moved into an unmaintained state and as such all open issues and pull requests will now be closed!

We’re happy to link to forks!
